services:
  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5436/docsEditorDB
      - --username=${DB_USERNAME}
      - --password=${DB_PASSWORD}
      - update
    volumes:
      - ./migrations:/changesets

  postgresql:
    image: postgres:17
    container_name: postgresDocsEditorDB
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: docsEditorDB
      PGPORT: 5436
    ports:
      - "5436:5436"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
