server:
  port: 8080
spring:
  application:
    name: docsEditor
  liquibase:
    enabled: false
  security:
    user:
      name: admin
      password: secret
      roles: ADMIN
  datasource:
    url: jdbc:postgresql://localhost:5436/docsEditorDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
app:
  jwt:
    secret: d3587b318c4720a6cc3eed4c7cf9f3819206ef76893fd025
    access-token-expires-ms: 9000000000
    refresh-token-expires-ms: 2592000000

# Настройки логирования
#logging:
#  level:
#    root: INFO
#    dsr.practice.docseditor: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging: DEBUG
#    org.springframework.security.messaging: TRACE
#    org.springframework.web.socket.config: DEBUG
#    org.springframework.web.socket.server: DEBUG
#    org.springframework.messaging.simp: DEBUG